#!/bin/sh
xrdb -load ~/.config/x11/.Xresources &

# Set Hotkeys
xmodmap ~/.config/x11/.Xmodmap &
exec autokey &
xcape -e 'Super_L=Escape' &
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
# exec ulauncher &

# Notification
dunst &

# Set wallpaper
# wal -q -i ~/.config/wallpapers/ &   # pywal
# feh --no-fehbg --bg-fill --randomize ~/.config/wallpapers/ &
# xwallpaper --zoom ~/.config/wallpapers/wall.jpg &
xwallpaper --zoom $(find ~/picture/Wallpapers -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1) &  # random bg

# Clipboard
#exec copyq &

# Start Alacritty
#/usr/bin/alacritty -e tmux & 

# Set Opacity
#compton &
picom &

# Music server & client
#mpd &
#mpDris2 &

# Start Window Manager
#dwmblocks &
exec dwm
#exec awesome
