xrdb -load ~/.config/x11/.Xresources &

# Set Hotkeys
xmodmap ~/.config/x11/.Xmodmap &
exec autokey &
xcape -e 'Super_L=Escape' &
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
# exec ulauncher &

# notification
dunst &

# Set wallpaper
# pywal
# wal -q -i ~/.config/wallpapers/ &
feh --no-fehbg --bg-fill --randomize ~/.config/wallpapers/ &
# xwallpaper --zoom ~/.config/wallpapers/wall.jpg &

# Clipboard
#exec copyq &

# Start Alacritty
#/usr/bin/alacritty -e tmux & 

# Set Opacity
#compton &
picom &

# Start Window Manager
#dwmblocks &
exec dwm
#exec awesome

